language: node_js
node_js:
  - "4.3.1"
  - "0.10"
script: make test-coverage
# after_success:
#   - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
after_success:
  - './node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info'
